In [1]:
import pandas as pd
import numpy as np

In [2]:
data=pd.read_csv('/content/sentiment_tweets3.csv')


In [3]:
data.shape


(10314, 3)

In [4]:
data.head(1)

Index                                 message to examine  \
0    106  just had a real good moment. i missssssssss hi...   

   label (depression result)  
0                          0

In [5]:
data.tail()

Index                                 message to examine  \
10309  802309  No Depression by G Herbo is my mood from now o...   
10310  802310  What do you do when depression succumbs the br...   
10311  802311  Ketamine Nasal Spray Shows Promise Against Dep...   
10312  802312  dont mistake a bad day with depression! everyo...   
10313  802313                                                  0   

       label (depression result)  
10309                          1  
10310                          1  
10311                          1  
10312                          1  
10313                          1

In [6]:
data.head()

Index                                 message to examine  \
0    106  just had a real good moment. i missssssssss hi...   
1    217         is reading manga  http://plurk.com/p/mzp1e   
2    220  @comeagainjen http://twitpic.com/2y2lx - http:...   
3    288  @lapcat Need to send 'em to my accountant tomo...   
4    540      ADD ME ON MYSPACE!!!  myspace.com/LookThunder   

   label (depression result)  
0                          0  
1                          0  
2                          0  
3                          0  
4                          0

**Data Preprocessing**

In [7]:
data.duplicated().sum()

0

In [8]:
data.isnull().sum()

Index                        0
message to examine           0
label (depression result)    0
dtype: int64

In [9]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10314 entries, 0 to 10313
Data columns (total 3 columns):
 #   Column                     Non-Null Count  Dtype 
---  ------                     --------------  ----- 
 0   Index                      10314 non-null  int64 
 1   message to examine         10314 non-null  object
 2   label (depression result)  10314 non-null  int64 
dtypes: int64(2), object(1)
memory usage: 241.9+ KB


In [10]:
data.describe()

Index  label (depression result)
count   10314.000000               10314.000000
mean   491253.470525                   0.224355
std    261688.134407                   0.417177
min       106.000000                   0.000000
25%    263019.250000                   0.000000
50%    514988.000000                   0.000000
75%    773521.500000                   0.000000
max    802313.000000                   1.000000

1.convert uppercase to lowercase
2.Remove Links
3.Remove Punctuations
4.Remove Numbers
5.Remove stopwords
6.Stemming

In [11]:
import re
import string

1.convert uppercase to lowercase

In [12]:
data['message to examine']=data['message to examine'].apply(lambda x:' '.join(x.lower() for x in x.split()))

In [13]:
data['message to examine'].head()

0    just had a real good moment. i missssssssss hi...
1            is reading manga http://plurk.com/p/mzp1e
2    @comeagainjen http://twitpic.com/2y2lx - http:...
3    @lapcat need to send 'em to my accountant tomo...
4         add me on myspace!!! myspace.com/lookthunder
Name: message to examine, dtype: object

2.Remove Liks

In [14]:
data['message to examine']=data['message to examine'].apply(lambda x:' '.join(re.sub(r'https?:\/\/.*[\r\n]*','',x,flags=re.MULTILINE) for x in x.split()))

In [15]:
data['message to examine'].head()

0    just had a real good moment. i missssssssss hi...
1                                    is reading manga 
2                                    @comeagainjen  - 
3    @lapcat need to send 'em to my accountant tomo...
4         add me on myspace!!! myspace.com/lookthunder
Name: message to examine, dtype: object

3.Remove Punctuations

In [16]:
def remove_punctuations(text):
  for punctuation in string.punctuation:
    text=text.replace(punctuation,'')
  return text


In [17]:
data['message to examine']=data['message to examine'].apply(remove_punctuations)

In [18]:
data['message to examine'].head()

0    just had a real good moment i missssssssss him...
1                                    is reading manga 
2                                      comeagainjen   
3    lapcat need to send em to my accountant tomorr...
4              add me on myspace myspacecomlookthunder
Name: message to examine, dtype: object

4.Remove Numbers

In [19]:
data['message to examine']=data['message to examine'].str.replace('\d+','',regex=True)

5.Remove Stopwords

In [20]:
import nltk

In [21]:
nltk.download('stopwords',download_dir='../static/model')

[nltk_data] Downloading package stopwords to ../static/model...
[nltk_data]   Unzipping corpora/stopwords.zip.


True

In [22]:
with open('../static/model/corpora/stopwords/english','r') as file:
   sw=file.read().splitlines()

In [23]:
sw

['i',
 'me',
 'my',
 'myself',
 'we',
 'our',
 'ours',
 'ourselves',
 'you',
 "you're",
 "you've",
 "you'll",
 "you'd",
 'your',
 'yours',
 'yourself',
 'yourselves',
 'he',
 'him',
 'his',
 'himself',
 'she',
 "she's",
 'her',
 'hers',
 'herself',
 'it',
 "it's",
 'its',
 'itself',
 'they',
 'them',
 'their',
 'theirs',
 'themselves',
 'what',
 'which',
 'who',
 'whom',
 'this',
 'that',
 "that'll",
 'these',
 'those',
 'am',
 'is',
 'are',
 'was',
 'were',
 'be',
 'been',
 'being',
 'have',
 'has',
 'had',
 'having',
 'do',
 'does',
 'did',
 'doing',
 'a',
 'an',
 'the',
 'and',
 'but',
 'if',
 'or',
 'because',
 'as',
 'until',
 'while',
 'of',
 'at',
 'by',
 'for',
 'with',
 'about',
 'against',
 'between',
 'into',
 'through',
 'during',
 'before',
 'after',
 'above',
 'below',
 'to',
 'from',
 'up',
 'down',
 'in',
 'out',
 'on',
 'off',
 'over',
 'under',
 'again',
 'further',
 'then',
 'once',
 'here',
 'there',
 'when',
 'where',
 'why',
 'how',
 'all',
 'any',
 'both',
 'each

In [ ]:
data['message to examine']=data['message to examine'].apply(lambda x:' '.join(x for x in x.split() if x not in sw ))

6.stemming

In [24]:
from nltk.stem import PorterStemmer
ps=PorterStemmer()

In [25]:
data['message to examine']=data['message to examine'].apply(lambda x:' '.join(ps.stem(x) for x in x.split()))

In [26]:
data['message to examine'].head()

0    just had a real good moment i missssssssss him...
1                                        is read manga
2                                         comeagainjen
3    lapcat need to send em to my account tomorrow ...
4                 add me on myspac myspacecomlookthund
Name: message to examine, dtype: object

Building Vocabulary

In [27]:
from collections import Counter
vocabulary=Counter()

In [28]:
for sentence in data['message to examine']:
  vocabulary.update(sentence.split())

In [29]:
len(vocabulary)

18824

In [30]:
tokens=[key for key in vocabulary if vocabulary[key]>10]

In [31]:
len(tokens)

1326

**2.Divide Dataset**

In [32]:
x=data['message to examine']
y=data['label (depression result)']

In [33]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.25)

vectorization

In [34]:
def vectorizer(ds,vocabulary):
  vectorized_list=[]
  for sentence in ds:
    sentence_list=np.zeros(len(vocabulary))
    for i in range(len(vocabulary)):
      if vocabulary[i] in sentence.split():
        sentence_list[i]=1
    vectorized_list.append(sentence_list)
  vectorized_list_new=np.asarray(vectorized_list,dtype=np.float32)
  return vectorized_list_new

In [35]:
vectorized_x_train=vectorizer(x_train,tokens)

In [36]:
vectorized_x_test=vectorizer(x_test,tokens)

In [37]:
vectorized_x_train

array([[0., 0., 1., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [1., 0., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.]], dtype=float32)

In [38]:
y_train.value_counts()

0    6000
1    1735
Name: label (depression result), dtype: int64

Handle inbalanced dataset

In [39]:
from imblearn.over_sampling import SMOTE
obj=SMOTE()
vectorized_x_train_SMOTE,y_train_SMOTE=obj.fit_resample(vectorized_x_train,y_train)

In [40]:
vectorized_x_train_SMOTE.shape

(12000, 1326)

In [41]:
y_train_SMOTE.value_counts()

0    6000
1    6000
Name: label (depression result), dtype: int64

In [42]:
from sklearn.metrics import accuracy_score,f1_score,precision_score,recall_score
def training_ACCURACY(y_actual,y_predicted):
  acc=accuracy_score(y_actual,y_predicted)
  pre=precision_score(y_actual,y_predicted)
  f1=f1_score(y_actual,y_predicted)
  re_score=recall_score(y_actual,y_predicted)
  print('training accuracy:','accuracy_score:',acc,'precision_score:',pre,'f1_score:',f1,'recall_score:',re_score)


In [43]:
from sklearn.metrics import accuracy_score,f1_score,precision_score,recall_score
def testing_ACCURACY(y_actual,y_predicted):
  acc=accuracy_score(y_actual,y_predicted)
  pre=precision_score(y_actual,y_predicted)
  f1=f1_score(y_actual,y_predicted)
  re_score=recall_score(y_actual,y_predicted)
  print('training accuracy:','accuracy_score:',acc,'precision_score:',pre,'f1_score:',f1,'recall_score:',re_score)

In [44]:

from sklearn.linear_model import LogisticRegression
from sklearn.naive_bayes import MultinomialNB
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC



Logistic Regression

In [45]:
lr_model=LogisticRegression()
lr_model.fit(vectorized_x_train_SMOTE,y_train_SMOTE)

LogisticRegression()

In [46]:
lr_pred=lr_model.predict(vectorized_x_train_SMOTE)

In [47]:
training_ACCURACY(y_train_SMOTE,lr_pred)

training accuracy: accuracy_score: 0.99375 precision_score: 1.0 f1_score: 0.9937106918238994 recall_score: 0.9875


In [48]:
y_test_pred=lr_model.predict(vectorized_x_test)

In [49]:
testing_ACCURACY(y_test,y_test_pred)


training accuracy: accuracy_score: 0.9872043427685149 precision_score: 0.9981751824817519 f1_score: 0.9707187222715172 recall_score: 0.9447322970639033


RandomForest

In [50]:
rf_model=RandomForestClassifier(n_estimators=50)
rf_model.fit(vectorized_x_train_SMOTE,y_train_SMOTE)

RandomForestClassifier(n_estimators=50)

In [51]:
rf_pred=rf_model.predict(vectorized_x_train_SMOTE)

In [52]:
training_ACCURACY(y_train_SMOTE,rf_pred)

training accuracy: accuracy_score: 0.9990833333333333 precision_score: 0.99983308295777 f1_score: 0.9990826453173214 recall_score: 0.9983333333333333


In [53]:
y_test_pred=rf_model.predict(vectorized_x_test)

In [54]:
testing_ACCURACY(y_test,y_test_pred)

training accuracy: accuracy_score: 0.9875920899573478 precision_score: 1.0 f1_score: 0.9715808170515097 recall_score: 0.9447322970639033


SVM

In [55]:
svm_model=SVC()
svm_model.fit(vectorized_x_train_SMOTE,y_train_SMOTE)

SVC()

In [56]:
svm_Pred=svm_model.predict(vectorized_x_train_SMOTE)

In [57]:
training_ACCURACY(y_train_SMOTE,svm_Pred)

training accuracy: accuracy_score: 0.9945833333333334 precision_score: 1.0 f1_score: 0.9945538332635107 recall_score: 0.9891666666666666


In [58]:
y_test_pred=svm_model.predict(vectorized_x_test)

In [59]:
testing_ACCURACY(y_test,y_test_pred)

training accuracy: accuracy_score: 0.9883675843350136 precision_score: 1.0 f1_score: 0.973404255319149 recall_score: 0.9481865284974094


**3.Prediction Pipeline**

In [60]:
def preprocessing(text):
  data=pd.DataFrame([text],columns=['message to examine'])
  data['message to examine']=data['message to examine'].apply(lambda x:' '.join(x.lower() for x in x.split()))
  data['message to examine']=data['message to examine'].apply(lambda x:' '.join(re.sub(r'^https?:\/\/.*','',x,flags=re.MULTILINE) for x in x.split()))
  data['message to examine']=data['message to examine'].apply(remove_punctuations)
  data['message to examine']=data['message to examine'].str.replace('\d+','',regex=True)
  data['message to examine']=data['message to examine'].apply(lambda x:' '.join(ps.stem(x) for x in x.split()))
  return data['message to examine']

In [71]:
def vectorizer(ds,vocabulary):
  vectorized_list=[]
  for sentence in ds:
    sentence_list=np.zeros(len(vocabulary))
    for i in range(len(vocabulary)):
      if vocabulary[i] in sentence.split():
        sentence_list[i]=1
    vectorized_list.append(sentence_list)
  vectorized_list_new=np.asarray(vectorized_list,dtype=np.float32)
  return vectorized_list_new


In [98]:
txt="just had a real good moment. i missssssssss hi..."
preprocess_data = preprocessing(txt)
pred_new = vectorizer(preprocess_data, tokens)





In [99]:
svm_pred=lr_model.predict(pred_new)

In [100]:
svm_pred

array([0])

In [101]:
txt="No Depression by G Herbo is my mood from now o...	"
preprocess_data = preprocessing(txt)
pred_new = vectorizer(preprocess_data, tokens)
svm_pred=lr_model.predict(pred_new)


In [102]:
svm_pred

array([1])

In [ ]:
#0-positive  1-negative